Issue 16/functions query
curiosum-dev/permit pull request #22
Opened 2022-10-01 00:34 UTC by Lisu11

2022-10-06 15:18 UTC, vincentvanbush requested changes

2022-10-06 20:37 UTC, vincentvanbush requested changes

2022-10-06 20:37 UTC, vincentvanbush commented on lib/permit/rules.ex
> +            # permission_to(authorization, unquote(name), resource, bindings, conditions)
unneeded - remove?

2022-10-06 20:37 UTC, vincentvanbush commented on lib/permit/rules.ex
> +          # @spec unquote(name)(Permit.t(), Types.resource(), Types.condition()) :: Permit.t()
I would like us to dig into this - it would be better if these generated functions did have typespecs. What error has made us comment this out now?

2022-10-06 20:37 UTC, vincentvanbush commented on lib/permit/types.ex
> +             (Types.subject(), struct() -> Ecto.Query.t())}
In `condition.ex` we have this as the type of the `:condition` key:
```elixir
          condition:
            boolean()
            | {atom(), (struct(), struct() -> any())}
            | (struct(), struct() -> boolean())
            | (struct() -> boolean()),
```
Some parts of this are matching, some are not. I'd like us to be able to have it delegated to `condition: Types.condition()`  in `condition.ex`, and also for this to be a bit more descriptive in some cases.
For example, `subject()` is a `struct()`, but `subject` describes it better in our domain. I'd like to see a similar clarification on what an `atom` is in this context (I think it's an action name but I'm not sure - generally atom could be anything, even a module), as well as what a `struct` is (is it the "object"?)

2022-10-07 11:48 UTC, Lisu11 commented on lib/permit/controller_authorization.ex
> +    preload = opts[:preload_fn]
if preaload_fn and (prefilter or postfilter) are defined throw an error

2023-02-17 15:33 UTC, vincentvanbush approved these changes

2023-02-17 15:34 UTC, merged